
/*
Permet d'inséret des valeurs aléatoires dans la table user'
*/

/*
t.n permet d'inséret le nombre du SELECT par le bié d'une table temporaire 't' '
*/

INSERT INTO user (email, roles, password, enabled, created_at, updated_at, emprunteur_id)
SELECT
CONCAT('user', t.n, '@example.com'),
'["ROLE_USER"]',
'123',
IF(t.n % 2 = 0, true, false),
NOW(),
NOW(),
FLOOR(RAND()*100)+1
FROM
(SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t
CROSS JOIN
(SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) u
LIMIT 100;



/*
Permet d'inséreet des valeurs aléatoires dans la table livre 
On ajoute des données aléatoires qui correspondent au thème du contenu 
le nombre de select dans les sous requêtes est à multipilié par la deuxième sous requête qui donne 10x10 donc 100 requête
*/
INSERT INTO livre (titre, annee_edition, nombre_pages, code_isbn, auteur_id)
SELECT
  CONCAT('Livre ', num) AS titre,
  FLOOR(RAND() * (2023 - 1900 + 1) + 1900) AS annee_edition,
  FLOOR(RAND() * (1000 - 50 + 1) + 50) AS nombre_pages,
  CONCAT(FLOOR(RAND() * 9000000000000 + 1000000000000)) AS code_isbn,
  FLOOR(RAND() * (4 - 1 + 1) + 1) AS auteur_id
FROM (
  SELECT 1 AS num UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10

) AS t1
CROSS JOIN (
  SELECT 1 AS a UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) AS t2
CROSS JOIN (
  SELECT 1 AS a UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) AS t3


LIMIT 1000;



INSERT INTO auteur (nom, prenom)
SELECT
  CONCAT('Nom', FLOOR(RAND() * 1000)) AS nom,
  CONCAT('Prenom', FLOOR(RAND() * 1000)) AS prenom
FROM ( SELECT 1 AS num  UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) t1
CROSS JOIN (
  SELECT 1 AS num  UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) t2
CROSS JOIN (
  SELECT 1 AS num  UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) t3
LIMIT 500;
